gcp/django/poll-app/app/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
]

# Only serve static files from Django during development
# Use Google Cloud Storage or an alternative CDN for production
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

gcp/django/poll-app/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

gcp/django/poll-app/polls/models.py
import datetime
from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

gcp/django/poll-app/polls/views.py
from django.http import HttpResponse, HttpRequest
from django.shortcuts import get_object_or_404, render
from .models import Question


def detail(request: HttpRequest, question_id: int):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


def results(request: HttpRequest, question_id: int):
    return HttpResponse(f"You're looking at the results of question {question_id}.")


def vote(request: HttpRequest, question_id: int):
    return HttpResponse(f"You're voting on question {question_id}.")


def index(request: HttpRequest):
    latest_questions = Question.objects.order_by('-pub_date')[:5]
    context = {
        'latest_questions': latest_questions,
    }
    return render(request, 'polls/index.html', context)

gcp/django/poll-app/polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}Django Question App{% endblock %}</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">
</head>

<body>
	{% load static %}
	<img src="{% static 'polls/header.jpg' %}" alt="My image">
	<section class="section">
		<div class="container">
			{% block content %}{% endblock %}
		</div>
	</section>
</body>
</html>

gcp/django/poll-app/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

gcp/django/poll-app/polls/templates/polls/index.html
{% extends 'polls/base.html' %}
{% block content %}
{% if latest_questions %}
    {% for question in latest_questions %}
	<div class="card">
		<div class="card-content">
			<div class="content">
				<a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
			</div>
		</div>
	</div>
    {% endfor %}
{% else %}
	<div class="tile">
		No polls are available.
	</div>
{% endif %}
{% endblock %}